/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package udla.cgarcia.poografica.progra.taller.s14.garcia.revelo.club;

import java.awt.HeadlessException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import static udla.cgarcia.poografica.progra.taller.s14.garcia.revelo.club.PrograTallerS14GarciaRevelo.club;
import udla.cgarcia.poografica.progra.taller.s14.garcia.revelo.club.Socio.Tipo;

/**
 *
 * @author Cristopher
 */
public class InterfazClub extends javax.swing.JFrame {
    
    private Club club = new Club();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfazClub.class.getName());

    /**
     * Creates new form InterfazClub
     */
    public InterfazClub() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        afiliarSocioButton = new javax.swing.JToggleButton();
        agregarSocioButton = new javax.swing.JToggleButton();
        eliminarAutorizadoButton = new javax.swing.JToggleButton();
        registrarConsumoButton = new javax.swing.JToggleButton();
        pagarFacturaButton = new javax.swing.JToggleButton();
        agregarFondoButton = new javax.swing.JToggleButton();
        mostrarSociosButton = new javax.swing.JToggleButton();
        verificarEliminacionButton = new javax.swing.JToggleButton();
        verConsumosButton = new javax.swing.JToggleButton();
        mostrarInfo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Administracion Club ");

        afiliarSocioButton.setText("1. Afiliar socio");
        afiliarSocioButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        afiliarSocioButton.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        afiliarSocioButton.addActionListener(this::afiliarSocioButtonActionPerformed);

        agregarSocioButton.setText("2. Agregar autorizado");
        agregarSocioButton.addActionListener(this::agregarSocioButtonActionPerformed);

        eliminarAutorizadoButton.setText("3. Eliminar autorizado");
        eliminarAutorizadoButton.addActionListener(this::eliminarAutorizadoButtonActionPerformed);

        registrarConsumoButton.setText("4. Registrar Consumo");
        registrarConsumoButton.addActionListener(this::registrarConsumoButtonActionPerformed);

        pagarFacturaButton.setText("5. Pagar Factura");
        pagarFacturaButton.addActionListener(this::pagarFacturaButtonActionPerformed);

        agregarFondoButton.setText("6. Agregar Fondo");
        agregarFondoButton.addActionListener(this::agregarFondoButtonActionPerformed);

        mostrarSociosButton.setText("7. Mostrar socios");
        mostrarSociosButton.addActionListener(this::mostrarSociosButtonActionPerformed);

        verificarEliminacionButton.setText("8. Verificar eliminacion");
        verificarEliminacionButton.addActionListener(this::verificarEliminacionButtonActionPerformed);

        verConsumosButton.setText("9. Ver  consumos");
        verConsumosButton.addActionListener(this::verConsumosButtonActionPerformed);

        mostrarInfo.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pagarFacturaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(registrarConsumoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(agregarFondoButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mostrarSociosButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(verificarEliminacionButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(verConsumosButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eliminarAutorizadoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(agregarSocioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(afiliarSocioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mostrarInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(afiliarSocioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(agregarSocioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eliminarAutorizadoButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(registrarConsumoButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pagarFacturaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(agregarFondoButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mostrarSociosButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(verificarEliminacionButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(verConsumosButton)
                        .addGap(0, 11, Short.MAX_VALUE))
                    .addComponent(mostrarInfo))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void afiliarSocioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afiliarSocioButtonActionPerformed
            afiliarSocioButton.setSelected(false); // Soltar botón
            try {
                String cedula = JOptionPane.showInputDialog(this, "Ingrese Cédula:");
                if(cedula == null) return;

                String nombre = JOptionPane.showInputDialog(this, "Ingrese Nombre:");
                if(nombre == null) return;

                String[] opts = {"Regular", "VIP"};
                int tipoSel = JOptionPane.showOptionDialog(this, "Tipo Socio", "Tipo", 
                        JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, opts, opts[0]);

                Tipo tipo = (tipoSel == 1) ? Tipo.VIP : Tipo.REGULAR;

                club.afiliarSocio(cedula, nombre, tipo);
                mostrarInfo.setText("Socio " + nombre + " afiliado con éxito.");
                JOptionPane.showMessageDialog(this, "Socio afiliado correctamente.");

            } catch (HeadlessException e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            } catch (Exception ex) {
                System.getLogger(InterfazClub.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
    }//GEN-LAST:event_afiliarSocioButtonActionPerformed

    private void agregarSocioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarSocioButtonActionPerformed
        agregarSocioButton.setSelected(false);
        try {
            String cedula = JOptionPane.showInputDialog(this, "Cédula del Socio:");
            if(cedula == null) return;
            
            String nombreAut = JOptionPane.showInputDialog(this, "Nombre del Autorizado:");
            if(nombreAut == null) return;
            
            club.agregarAutorizadoSocio(cedula, nombreAut);
            mostrarInfo.setText("Autorizado " + nombreAut + " agregado.");
            JOptionPane.showMessageDialog(this, "Autorizado agregado correctamente.");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_agregarSocioButtonActionPerformed

    private void eliminarAutorizadoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarAutorizadoButtonActionPerformed
        eliminarAutorizadoButton.setSelected(false);
        try {
            String cedula = JOptionPane.showInputDialog(this, "Cédula del Socio:");
            if(cedula == null) return;
            
            String nombreAut = JOptionPane.showInputDialog(this, "Nombre Autorizado a eliminar:");
            if(nombreAut == null) return;
            
            club.eliminarAutorizadoSocio(cedula, nombreAut);
            mostrarInfo.setText("Autorizado eliminado.");
            JOptionPane.showMessageDialog(this, "Autorizado eliminado correctamente.");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_eliminarAutorizadoButtonActionPerformed

    private void registrarConsumoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarConsumoButtonActionPerformed
        registrarConsumoButton.setSelected(false);
        try {
            String cedula = JOptionPane.showInputDialog(this, "Cédula del Socio Titular:");
            if(cedula == null) return;
            
            String cliente = JOptionPane.showInputDialog(this, "¿Quién consume? (Nombre Socio o Autorizado):");
            if(cliente == null) return;
            
            String concepto = JOptionPane.showInputDialog(this, "Concepto:");
            String valorStr = JOptionPane.showInputDialog(this, "Valor ($):");
            
            double valor = Double.parseDouble(valorStr);
            
            club.registrarConsumo(cedula, cliente, concepto, valor);
            mostrarInfo.setText("Consumo registrado por $" + valor);
            JOptionPane.showMessageDialog(this, "Consumo registrado exitosamente.");
            
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Ingrese un número válido", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_registrarConsumoButtonActionPerformed

    private void pagarFacturaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagarFacturaButtonActionPerformed
        pagarFacturaButton.setSelected(false);
        try {
            String cedula = JOptionPane.showInputDialog(this, "Cédula del Socio:");
            if(cedula == null) return;
            
            ArrayList<Factura> facts = club.darFacturasSocio(cedula);
            if(facts.isEmpty()) {
                mostrarInfo.setText("No hay facturas pendientes.");
                JOptionPane.showMessageDialog(this, "El socio no tiene facturas pendientes.");
                return;
            }
            
            // Crear lista para el popup
            String[] lista = new String[facts.size()];
            for(int i=0; i<facts.size(); i++) {
                lista[i] = i + ". " + facts.get(i).toString();
            }
            
            String sel = (String) JOptionPane.showInputDialog(this, "Seleccione Factura", "Pagar",
                    JOptionPane.QUESTION_MESSAGE, null, lista, lista[0]);
            
            if(sel != null) {
                int indice = Integer.parseInt(sel.split("\\.")[0]);
                club.pagarFacturaSocio(cedula, indice);
                mostrarInfo.setText("Factura pagada exitosamente.");
                JOptionPane.showMessageDialog(this, "Factura pagada con éxito.");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_pagarFacturaButtonActionPerformed

    private void agregarFondoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarFondoButtonActionPerformed
        agregarFondoButton.setSelected(false);
        try {
            String cedula = JOptionPane.showInputDialog(this, "Cédula del Socio:");
            if(cedula == null) return;
            
            String montoStr = JOptionPane.showInputDialog(this, "Monto a agregar ($):");
            if(montoStr == null) return;
            
            double monto = Double.parseDouble(montoStr);
            club.aumentarFondosSocio(cedula, monto);
            mostrarInfo.setText("Fondos aumentados. $" + monto);
            JOptionPane.showMessageDialog(this, "Fondos aumentados correctamente.");    
            
        } catch (NumberFormatException nfe) {
             JOptionPane.showMessageDialog(this, "Monto inválido", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_agregarFondoButtonActionPerformed

    private void mostrarSociosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarSociosButtonActionPerformed
        mostrarSociosButton.setSelected(false);
        ArrayList<Socio> lista = club.darSocios();
        
        if(lista.isEmpty()) {
            mostrarInfo.setText("No hay socios registrados.");
            JOptionPane.showMessageDialog(this, "No hay socios.");
        } else {
            StringBuilder sb = new StringBuilder();
            for(Socio s : lista) {
                sb.append(s.toString()).append("\n");
                sb.append(" - Autorizados: ").append(s.darAutorizados()).append("\n");
                sb.append(" - Facturas: ").append(s.darFacturas().size()).append("\n\n");
            }
            mostrarInfo.setText("Lista mostrada en ventana.");
            JOptionPane.showMessageDialog(this, sb.toString(), "Lista de Socios", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_mostrarSociosButtonActionPerformed

    private void verificarEliminacionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verificarEliminacionButtonActionPerformed
        verificarEliminacionButton.setSelected(false);
        try {
            String cedula = JOptionPane.showInputDialog(this, "Cédula a verificar:");
            if(cedula == null) return;
            
            boolean puede = club.sePuedeEliminarSocio(cedula);
            if(puede) {
                mostrarInfo.setText("SÍ se puede eliminar.");
                JOptionPane.showMessageDialog(this, "El socio CUMPLE los requisitos para ser eliminado.");
            }
        } catch (Exception e) {
            mostrarInfo.setText("NO se puede eliminar.");
            JOptionPane.showMessageDialog(this, "NO SE PUEDE: " + e.getMessage(), "Alerta", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_verificarEliminacionButtonActionPerformed

    private void verConsumosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verConsumosButtonActionPerformed
        verConsumosButton.setSelected(false);
        try {
            String cedula = JOptionPane.showInputDialog(this, "Cédula del Socio:");
            if(cedula == null) return;
            
            double total = club.calcularTotalConsumos(cedula);
            mostrarInfo.setText("Deuda Total: $" + total);
            JOptionPane.showMessageDialog(this, "El total de facturas pendientes es: $" + total);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_verConsumosButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InterfazClub().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton afiliarSocioButton;
    private javax.swing.JToggleButton agregarFondoButton;
    private javax.swing.JToggleButton agregarSocioButton;
    private javax.swing.JToggleButton eliminarAutorizadoButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField mostrarInfo;
    private javax.swing.JToggleButton mostrarSociosButton;
    private javax.swing.JToggleButton pagarFacturaButton;
    private javax.swing.JToggleButton registrarConsumoButton;
    private javax.swing.JToggleButton verConsumosButton;
    private javax.swing.JToggleButton verificarEliminacionButton;
    // End of variables declaration//GEN-END:variables
}
